DEBUG: True
ENABLE_STREAMING: True
HOST: "0.0.0.0"
LLM_PROVIDERS:
  [
    { anthropic: "langchain_anthropic.ChatAnthropic" },
    { google: "langchain_google.ChatGoogleGenerativeAI" },
    { mistral: "langchain_mistral.ChatMistralAI" },
    { openai: "langchain_openai.ChatOpenAI" },
  ]
MAX_CONCURRENT_REQUESTS: 10
PORT: 5050
PRODUCTION_MODE: False
PRODUCTION_ENDPOINT: "https://cmr.earthdata.nasa.gov/search/"
REQUEST_TIMEOUT: 30
STREAM_CHUNK_SIZE: 10
TEST_ENDPOINT: "https://cmr.uat.earthdata.nasa.gov/search/"
