AVAILABLE_LLM_PROVIDERS:
  - name: Anthropic
DEBUG: True
ENABLE_STREAMING: True
HOST: "0.0.0.0"
LOG_FOLDER_PATH: "logs"
MAX_CONCURRENT_REQUESTS: 10
PORT: 5050
PRODUCTION_MODE: False
PRODUCTION_ENDPOINT: "https://cmr.earthdata.nasa.gov/search/"
PROMPT_FOLDER_PATH: "prompts"
REQUEST_TIMEOUT: 30
STREAM_CHUNK_SIZE: 10
TEST_ENDPOINT: "https://cmr.uat.earthdata.nasa.gov/search/"
USE_LANGSMITH: False