version: '3.8'
services:
  ubuntu:
    container_name: nasa_cmr_agent_container
    build:
      context: .
      dockerfile: Dockerfile
    image: nasa_cmr_agent_image
    command: sleep infinity
    volumes:
      - .:/home/vscode/.devcontainer
